version: '3.8' 
volumes:
  postgres_data:
      driver: local 
services:
  postgres:
      container_name: keycloak-db
      image: postgres:14.6
      env_file:
        - ./keycloak-postgres.env
      volumes:
        - ./data-db:/var/lib/postgresql/data
      ports:
        - 5432:5432
      restart: unless-stopped
  keycloak:
      container_name: keycloak-server
      image: quay.io/keycloak/keycloak:18.0.2
      env_file:
        - ./keycloak-postgres.env
      environment:
        KC_FEATURES: preview
      entrypoint: /opt/keycloak/bin/kc.sh start --auto-build
      volumes:
        - ./keycloak-config:/opt/keycloak/conf
      ports:
        - 8080:8080
        - 443:8443
      restart: unless-stopped
      depends_on:
        - postgres
#networks:
#  default:
#    name: my-main-net external: true Note: Generate a self signed certificate in ./keycloak-config folder openssl req -newkey rsa:2048 -nodes -keyout keycloak-server.key.pem -x509 -days 3650 -out keycloak-server.crt.pem
#-out keycloak-server.crt.pem
# use -proxy reencrypt if nginx comunicate over HTTPS with keycloak; use -proxy egde if nginx comunicate over HTTP with keycloak;
