version: "3.7"

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data 
      - ./data/caddy/config:/config 
    networks:
      - web
      - internal

  ghost:
    image: ghost:4-alpine
    restart: unless-stopped
    environment:
      - url=https://myghost.mydomain.com 
    volumes:
      - ./data/myghostapp:/var/lib/ghost/content
    networks:
      - internal