services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - '/home/ubuntu/docker/vaultwarden/:/data/'
    restart: unless-stopped
    networks:
      my-main-net:
    security_opt:
      - no-new-privileges:true

networks:
  my-main-net:
    external: true