services:
  check-mk-raw:
    ports:
      - '8085:5000'
    tmpfs: '/opt/omd/sites/cmk/tmp:uid=1000,gid=1000'
    volumes:
      - './monitoring:/omd/sites'
    container_name: checkmk
    restart: always
    image: 'checkmk/check-mk-raw:2.4.0-latest'
    environment:
      - CMK_PASSWORD=changeme
      - TZ=Europe/Bucharest

#networks:
#  default:
#    name: my-main-net
#    external: true
