version: '3.1'

volumes:
  redmine_data: {}

services:

  redmine:
    image: redmine
    container_name: redmine
    restart: always
    ports:
      - 8080:3000
    volumes:
      - redmine_data:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    container_name: redmine_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine