services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Bucharest
      - SETTINGS_ENCRYPTION_KEY=abracadabra
    volumes:
      - ./config:/config
      - ./backups:/backups
      - /home/cosmin/:/source
    ports:
      - 8270:8200
    restart: unless-stopped