version: "3"
services:
  keycloak:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:20.0
#    volumes:
#      - ./themes/sometheme/:/opt/keycloak/themes/sometheme/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - 8080:8080
