---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My First Group:
    - My First Service:
        icon: sonarr.png #check https://github.com/walkxcode/dashboard-icons/tree/main/png
        href: http://localhost/
        description: Homepage is awesome
    - My First Service 2:
        href: http://localhost/
        description: Homepage is awesome    
    - My First Service 3:
        href: http://localhost/
        description: Homepage is awesome     

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
