#version: '3.1'

services:

  ghost:
    image: ghost:5-alpine
    container_name: ghost
    restart: always
    #ports:
    #  - 8082:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:2368
      #url: https://blog.pakithecat.eu
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ./ghost:/var/lib/ghost/content

  db:
    image: mysql:8.0
    container_name: ghost-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql

networks:
  default:
    name: my-main-net
    external: true
