version: '3.7'

services:
  
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9090:9090" 
    environment:
      MINIO_ROOT_PASSWORD: pickme
      MINIO_ROOT_USER: pickme
    command: server /data --console-address ":9090" 
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
